# Generated by Django 3.0.7 on 2020-11-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='how_rejected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='how_rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
