# Generated by Django 3.0.7 on 2020-10-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201017_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Account',
            new_name='account',
        ),
    ]
