# Generated by Django 3.0.6 on 2020-05-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
