# Generated by Django 3.0.7 on 2020-11-14 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0002_auto_20201108_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('carbs', models.FloatField()),
                ('category', models.IntegerField(choices=[(1, 'Meats'), (2, 'Vegetables'), (3, 'Fruits'), (4, 'Baking'), (5, 'Sweets')])),
                ('for_every_one', models.BooleanField(default=False)),
                ('patient', models.ManyToManyField(related_name='food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
