# Generated by Django 3.0.7 on 2020-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.IntegerField(choices=[(1, 'Meats'), (2, 'Vegetables'), (3, 'Fruits'), (4, 'Baking'), (5, 'Sweets'), (6, 'Other')], default=6),
        ),
    ]
