# Generated by Django 3.0.7 on 2020-10-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20201027_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_cooperate', to='Api.Doctor'),
        ),
        migrations.AlterField(
            model_name='cooperate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_cooperate', to='Api.Patient'),
        ),
    ]
