# Generated by Django 3.0.6 on 2020-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200524_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='msg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
