# Generated by Django 3.0.6 on 2020-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_email_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
