# Generated by Django 3.0.4 on 2020-04-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0004_auto_20200405_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
