# Generated by Django 3.0.7 on 2020-10-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20201027_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperate',
            old_name='messagge',
            new_name='message',
        ),
    ]
