# Generated by Django 3.0.4 on 2020-04-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20200407_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sugar_leve',
        ),
        migrations.AddField(
            model_name='sugar_level',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugar', to='Api.Patient'),
        ),
    ]
