# Generated by Django 3.0.7 on 2020-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20201029_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperate',
            name='show_rejected_first_time',
            field=models.BooleanField(default=False),
        ),
    ]
