# Generated by Django 3.0.4 on 2020-04-07 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20200407_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugar_level',
            name='patient',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='sugar', to='Api.Patient'),
            preserve_default=False,
        ),
    ]
